openapi: 3.0.3
info:
  title: Swagger Categorie Prodotti REST - OpenAPI 3.0
  description: |-
    Servizio per la gestione delle categorie dei prodotti.

    _If you're looking for the Swagger 2.0/OAS 2.0 version of SpeseManager, then click [here](https://editor.swagger.io/?url=https://petstore.swagger.io/v2/swagger.yaml). Alternatively, you can load via the `Edit > Load Petstore OAS 2.0` menu option!_
    
  termsOfService: http://swagger.io/terms/
  contact:
    email: enrico.trx@hotmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: http://localhost:8080/CategorieProdServ/
tags:
  - name: CategoriaProd
    description: Tutto riguardo le categorie dei tuoi prodotti
paths:
  /CategoriaProd:
  
    get:
      tags:
        - CategoriaProd
      summary: Ottieni le tutte categorie di prodotti esistenti
      description: Ottieni le tutte categorie di prodotti esistenti
      operationId: elencoCategorieProd
      responses:
        '200':
          description: Operazione eseguita con successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CategoriaProd'    
            application/xml:
              schema:
                $ref: '#/components/schemas/CategoriaProd'                
        '404':
          description: Categorie prodotti non trovate
        '500':
          description: Internal Server Error
          
    post:
      tags:
        - CategoriaProd
      summary: Aggiungi una nuova categoria prodotto
      description: Aggiungi una nuova categoria prodotto
      operationId: creaCategoriaProd
      requestBody:
        description: Crea una nuova spesa nel manager
        content:
          application/json:
              schema:
                $ref: '#/components/schemas/CategoriaProd'    
          application/xml:
              schema:
                $ref: '#/components/schemas/CategoriaProd'   
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/CategoriaProd'
        required: true
      responses:
        '200':
          description: Operazione eseguita con successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CategoriaProd'          
            application/xml:
              schema:
                $ref: '#/components/schemas/CategoriaProd'
        '405':
          description: Input non valido
            
  /CategoriaProd/{id}:
    get:
      tags:
        - CategoriaProd
      summary: Trova categoria dall'ID (hashed))
      description: Ritorna una singola categoria
      operationId: getCategoriaProd
      parameters:
        - name: id
          in: path
          description: ID della categoria da ritornare
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Operazione eseguita con successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CategoriaProd'          
            application/xml:
              schema:
                $ref: '#/components/schemas/CategoriaProd'
        '400':
          description: ID fornito non valido
        '404':
          description: Categoria prodotto non trovata
          
    delete:
      tags:
        - CategoriaProd
      summary: Cancella una categoria
      description: cancella una categoria dato l'id
      operationId: cancellaCategoriaProd
      parameters:
        - name: api_key
          in: header
          description: ''
          required: false
          schema:
            type: string
        - name: id
          in: path
          description: ID della categoria da eliminare
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Operazione riuscita!
        '400':
          description: ID fornito non valido
                
components:
  schemas:

    
    CategoriaProd:
      required:
        - nome
      type: object
      properties:
        id_categoria_prodotto:
          type: integer
          format: int64
          example: 10
        nome:
          type: string
          example: 'Salumi'
         
    ApiResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        type:
          type: string
        message:
          type: string
      xml:
        name: '##default'
  requestBodies:
    CategoriaProd:
      description: oggetto CategoriaProd da aggiungere al registro
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CategoriaProd'
        application/xml:
          schema:
            $ref: '#/components/schemas/CategoriaProd'